### ISSUE TITLE
Latest build is broken

### ISSUE THREAD

**Issue by berendt** [osism/container-images-kolla#104]
```
INFO:***.common.utils:Found the docker image folder at /opt/hostedtoolcache/Python/3.9.7/x64/share/***/docker
34
Traceback (most recent call last):
35
  File "/opt/hostedtoolcache/Python/3.9.7/x64/bin/***-build", line 10, in <module>
36
    sys.exit(main())
37
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/***/cmd/build.py", line 33, in main
38
    statuses = build.run_build()
39
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/***/image/build.py", line 1376, in run_build
40
    ***.create_dockerfiles()
41
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/***/image/build.py", line 907, in create_dockerfiles
42
    content = template.render(values, env=os.environ)
43
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
44
    self.environment.handle_exception()
45
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
46
    reraise(*rewrite_traceback_stack(source=source))
47
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
48
    raise value.with_traceback(tb)
49
  File "<template>", line 34, in top-level template code
50
  File "/tmp/***-2021-10-03_10-13-56_n96m8en3/docker/fluentd/Dockerfile.j2", line 20, in top-level template code
51
    {{ macros.enable_extra_repos(['td-agent']) }}
52
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/jinja2/runtime.py", line 679, in _invoke
53
    rv = self._func(*arguments)
54
  File "/tmp/***-2021-10-03_10-13-56_n96m8en3/docker/macros.j2", line 74, in template
55
    {{ handle_repos(repos, 'enable') }}
56
  File "/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/***/template/methods.py", line 118, in handle_repos
57
    commands += f"""echo 'Uris: {repo_list[repo]['url']}' \
58
TypeError: string indices must be integers
59
```

**Comment by osfrickler** [comment]
The format for `repos.yaml` has been changed with https://review.opendev.org/c/openstack/kolla/+/784923 , need to adapt our override accordingly.
